FROM docker.io/alpine:3.21.3
RUN apk add --update --no-cache python3 openssl
WORKDIR /usr/src/hostinfo
COPY ./hostinfo_server.py .
RUN chown 1000:1000 hostinfo_server.py && chmod 500 hostinfo_server.py
LABEL org.opencontainers.image.ref.name=hostinfo
LABEL org.opencontainers.image.version=1.0.0-python
LABEL org.opencontainers.image.authors=rx-m
LABEL org.opencontainers.image.url=https://rx-m.com
USER 1000:1000
ENV PYTHONUNBUFFERED=1
ENTRYPOINT ["./hostinfo_server.py"]
CMD ["9898"]
